spring:
  cloud:
    stream:
      default-binder: solaceBroker
      bindings:
        join_request:
          destination: JOIN-REQUESTS
          group: SOLACE-BATTLESHIP
          binder: solaceBroker
        board_set_request:
          destination: BOARD-SET-REQUESTS
          group: SOLACE-BATTLESHIP
          binder: solaceBroker
      binders:
        solaceBroker:
          type: solace
          environment:
            solace:
              java:
                connectRetries: 3
                connectRetriesPerHost: 0
                reconnectRetries: 3
      solace:
        bindings:
          join_request:
            consumer:
              queueAdditionalSubscriptions: SOLACE/BATTLESHIP/*/JOIN-REQUEST/*
          board_set_request:
            consumer:
              queueAdditionalSubscriptions: SOLACE/BATTLESHIP/*/BOARD-SET-REQUEST/*
logging:
  level:
    root: INFO
    com.solacesystems.jcsmp: INFO
    org.springframework: INFO
    
server:
  port: 8094